# General settings
tab_width = 4
keyboard_scroll_lines = 3
double_tap_speed_ms = 300
mouse_scroll_lines = 3

# Syntax settings
[syntax]
enable = true
max_bytes = 500000
# Directories to search for Nano syntax files (*.nanorc)
dirs = ["~/.ue/syntax/"]
# Map alternative file extensions or names to a base extension
extension_aliases = { zshrc = "sh", zsh = "sh", profile = "sh", ue = "json" }

# Appearance settings
[appearance]
line_number_digits = 3
header_bg = "#001848"
footer_bg = "#001848"
line_numbers_bg = "#001848"
# Cursor shape: "bar" | "block" | "underline"
cursor_shape = "bar"

# Keybindings
[keybindings]
quit = "Esc Esc"
file_selector = "Esc"
copy = "Ctrl+c"
paste = "Ctrl+v"
cut = "Ctrl+x"
close = "Ctrl+w"
save = "Ctrl+s"
undo = "Ctrl+z"
redo = "Ctrl+y"

