# General settings
tab_width = 4
keyboard_scroll_lines = 3
double_tap_speed_ms = 300
mouse_scroll_lines = 3
# Enable line wrapping (true) or horizontal scrolling (false)
line_wrapping = true


# Appearance settings
[appearance]
line_number_digits = 3
header_bg = "#001848"
footer_bg = "#001848"
line_numbers_bg = "#001848"
# Cursor shape: "bar" | "block" | "underline"
cursor_shape = "bar"

# Keybindings
[keybindings]
quit = "Esc Esc"
file_selector = "Esc"
copy = "Ctrl+c"
paste = "Ctrl+v"
cut = "Ctrl+x"
close = "Ctrl+w"
save = "Ctrl+s"
undo = "Ctrl+z"
redo = "Ctrl+y"
find = "Ctrl+f"
find_next = "Ctrl+n"
find_previous = "Ctrl+p"
goto_line = "Ctrl+g"
help = "F1"
save_and_quit = "Ctrl+q"

